### ISSUE TITLE
Ebay

### ISSUE THREAD

**Issue by pfsenseuser** [compvid30/scriptblock#44]
Ebay is not working unless ScriptBlock is deactivated (all ebay domains are on the whitelist). This can be reproduced under Chrome & Chromium 101, Opera 87 (based on chrome 101) and also on Brave (based on chrome 102) under Linux, Windows and also MacOSX.

**Comment by GlitterHorn** [comment]
+1 can confirm. I whitelisted everything that showed up in uMatrix (with ScriptBlock disabled), and it's still crashing.

**Comment by mmortal03** [comment]
Yep, came here to mention this. Browsing to eBay freezes the page, such that you can't click on the search bar at the top, and will stop responding. Usually, when a site freezes like this due to ScriptBlock, you just have to add it to the whitelist manually -- but, in this case, that doesn't help. 

Does anyone know of any alternative JavaScript blocker for Chrome that is actively supported by its devs, applies its whitelist to all subdomains, and has a temp allow (e.g. session allow) option? If there was something like that that I could just copy and paste my whitelist into, I'd switch immediately.

**Comment by pfsenseuser** [comment]
> Does anyone know of any alternative JavaScript blocker for Chrome that is actively supported by its devs, applies its whitelist to all subdomains, and has a temp allow (e.g. session allow) option? If there was something like that that I could just copy and paste my whitelist into, I'd switch immediately.

You can (if you want) switch to NoScript - its now available for the majority browsers (Firefox, and all Chrome-Engine based Browsers).

**Comment by mmortal03** [comment]
Is there any way to determine which part of the ebay code is causing it to hang? Maybe this could be filtered out for the time being using a different extension?

**Comment by rbronco21** [comment]
Here are my exceptions. I think ebaystatic is the one that is hard to find. If this doesn't help, let me know and I'll do a more thorough search through my exceptions.

ebay.com
ebay-us.com
ebaystatic.com

**Comment by mmortal03** [comment]
@rbronco21 , In this case, with eBay, the page freezes even if you Temporarily allow scripts globally -- it doesn't seem to matter if you've added those exceptions or not, unfortunately.

**Comment by rbronco21** [comment]
> @rbronco21 , In this case, with eBay, the page freezes even if you Temporarily allow scripts globally -- it doesn't seem to matter if you've added those exceptions or not, unfortunately.

I ran a couple Chrome profiles a while ago and I spent forever trying to get the new ones working. I finally gave up and went back to my original profile. There is hope, I just don't know what it is if those exceptions didn't help. I'd be happy to provide logs and settings to the dev if it would help see why this profile works.

**Comment by mmortal03** [comment]
> I'd be happy to provide logs and settings to the dev if it would help see why this profile works.

If you can, that'd be great. I have no idea why it would work on one Chrome profile but not others. I'd just assumed it was broken on eBay in all circumstances.

**Comment by yremogtnom** [comment]
I believe I found a workaround for this.
If you go into the safelist and change **"ebay.com"** to **"*.ebay.com"**, and likewise change **"ebaystatic.com"** to **"*.ebaystatic.com"**, the site does allow navigation (after relaunching it in a new tab/window.)  

This was plaguing me for months.  Disabling security should not be an option.  I was instead using incognito, but ended up very frustrated because I was trying to perform some tasks requiring multiple windows, and they weren't working together.  This was a "Hail Mary" play that turned out to work.

Also sending this fix via the "Contact the Publisher" to let them know via that route as well so they might look into why that works.

**Comment by mmortal03** [comment]
@yremogtnom , unfortunately, it didn't work for me. To be sure, I did not include the quotes and I made sure to click save. It makes me wonder why it would work for you, but not for me. :(

**Comment by yremogtnom** [comment]
@mmortal03  - I tried this in Windows 11, and it worked
I went and tried it in Windows 7, and it did not.  I don't have Windows 10 to try it in at this time ...
But it worked in 11 using Chrome and this extension.  Now that I know it didn't work in my Windows 7 machine, it's not as good a breakthrough as I thought it was.

**Comment by Hamst3r** [comment]
I'm having this problem too. Windows 10, Chrome Version 112.0.5615.121, ScriptBlock Version 1.3.0. Every ebay domain whitelisted, even tried the adding a *. before each domain trick.

**Comment by mmortal03** [comment]
@yremogtnom , unfortunately, I don't have a Windows 11 machine easily available to test. I know of no context where Chrome would act differently in this way on Windows 11, but not Windows 7 or 10, but maybe there is. Really weird.

**Comment by mmortal03** [comment]
I just noticed that it's also doing this on uber.com, after sign in.

**Comment by b2gills** [comment]
If you hit <kbd>F12</kbd>, it shows this in the console area

```
blockStart.js:56 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.has (chrome-extension://hcdjknjpbnhdoabbngpmfekaecnpajba/blockStart.js:56:18)
    at chrome-extension://hcdjknjpbnhdoabbngpmfekaecnpajba/blockStart.js:110:20
blockStart.js:211 Uncaught TypeError: Cannot read properties of undefined (reading 'globalAllowAll')
    at isGloballyAllowed (blockStart.js:211:31)
    at blockAfter.js:4:53
31yzqmzxk3a3utciscis2t10n1uu.js:7 943 1920
blockStart.js:56 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.has (chrome-extension://hcdjknjpbnhdoabbngpmfekaecnpajba/blockStart.js:56:18)
    at chrome-extension://hcdjknjpbnhdoabbngpmfekaecnpajba/blockStart.js:110:20
blockStart.js:56 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.has (chrome-extension://hcdjknjpbnhdoabbngpmfekaecnpajba/blockStart.js:56:18)
    at chrome-extension://hcdjknjpbnhdoabbngpmfekaecnpajba/blockStart.js:110:20
blockStart.js:211 Uncaught TypeError: Cannot read properties of undefined (reading 'globalAllowAll')
    at isGloballyAllowed (blockStart.js:211:31)
    at blockAfter.js:4:53
blockStart.js:211 Uncaught TypeError: Cannot read properties of undefined (reading 'globalAllowAll')
    at isGloballyAllowed (blockStart.js:211:31)
    at blockAfter.js:4:53
```

**Comment by mmortal03** [comment]
For me with this bug the tab locks up, so hitting F12 afterwards does nothing. I also don't get anything if Developer tools -> console is open beforehand.

**Comment by b2gills** [comment]
I only managed to get to see that console after multiple attempts.

**Comment by mattcintosh** [comment]
Ebay is broke again. My selling pages (my.ebay.com/ws/eBayISAPI.dll?MyEbayBeta&CurrentPage=MyeBayNextAllSelling) freeze up the page and even with "allow all scripts" still doesn't work. I have to completely disable the extension for ebay to actually work without freezing.
